config/routes.rb
Curaduria::Application.routes.draw do
  
  resources :data, :users, :sessions

  root 'home#index'
  get 'normatividad' => 'home#normatividad'
  get 'servicios'    => 'home#servicios'
  get 'misionv'     => 'home#misionv'
  get 'nuestrasede'  => 'home#nuestrasede'
  get 'contacto'   => 'home#contacto'
  get 'liquidacion_de_expensas' => 'liq_expensas#index'
  get 'cargo_fijo_uso_residencial' => 'liq_expensas#cf_ur'
  get 'cargo_variable_uso_residencial' => 'liq_expensas#cv_ur'
  get 'cargo_fijo_otros_usos' => 'liq_expensas#cf_ou'
  get 'cargo_variable_otros_usos' => 'liq_expensas#cv_ou'
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "sign_up" => "users#new", :as => "sign_up"
  get "adm_board" => "data#index", :as => "adm_board"
  get "decreto_1469" => "pdfs#decreto_1469", :as => "decreto_1469"
  get "decreto_4397" => "pdfs#decreto_4397", :as => "decreto_4397"
  get "ley_388" => "pdfs#ley_388", :as => "ley_388"
  get "estatuto_urbano" => "pdfs#estatuto_urbano", :as => "estatuto_urbano"


end

app/models/datum.rb
class Datum < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :password
	before_save :encrypt_password

	validates_confirmation_of :password
	validates_presence_of :name
	validates_uniqueness_of :name

	def self.authenticate(name, password)
		user = User.where(name: name).first
		if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
			user
		else
			nil
		end

	end

	def encrypt_password
		if password.present?
			self.password_salt = BCrypt::Engine.generate_salt
			self.password_hash = BCrypt::Engine.hash_secret(password,password_salt)

		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
    helper_method :current_user
private


def current_user
@current_user ||= User.find(session[:user_id])if session[:user_id]
end
end

app/controllers/data_controller.rb
class DataController < ApplicationController
  before_action :set_datum, only: [:show, :edit, :update, :destroy]

  # GET /data
  # GET /data.json
  def index
    @data = Datum.all
  end

  # GET /data/1
  # GET /data/1.json
  def show
  end

  # GET /data/new
  def new
    @datum = Datum.new
  end

  # GET /data/1/edit
  def edit
  end

  # POST /data
  # POST /data.json
  def create
    @datum = Datum.new(datum_params)

    respond_to do |format|
      if @datum.save
        format.html { redirect_to @datum, notice: 'Datum was successfully created.' }
        format.json { render action: 'show', status: :created, location: @datum }
      else
        format.html { render action: 'new' }
        format.json { render json: @datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /data/1
  # PATCH/PUT /data/1.json
  def update
    respond_to do |format|
      if @datum.update(datum_params)
        format.html { redirect_to @datum, notice: 'Datum was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /data/1
  # DELETE /data/1.json
  def destroy
    @datum.destroy
    respond_to do |format|
      format.html { redirect_to data_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_datum
      @datum = Datum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def datum_params
      params.require(:datum).permit(:definicion, :anio, :siglas, :valor)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end 
  def normatividad
  end 
  def servicios
  end
  def contacto
  end
  def quienes
  end
  def misionv
  end
  def nuestrasede
  end


end

app/controllers/liq_expensas_controller.rb
class LiqExpensasController < ApplicationController

def index
  @data= Datum.all 
end

def cf_ur
  @data= Datum.all 
  render :layout => false
end

def cv_ur
  @data= Datum.all 
   render :layout => false
end

def cf_ou
  @data= Datum.all 
  render :layout => false
end

def cv_ou
  @data= Datum.all 
  render :layout => false
end

end

app/controllers/pdfs_controller.rb
class PdfsController < ApplicationController

	def decreto_1469
		path=Rails.root.join('public','Decreto_1469_de_2010.pdf')
	  send_file(path, :type => 'application/pdf', :disposition => 'inline')
	end

	def decreto_4397
		path=Rails.root.join('public','Decreto_4397_de_2006.pdf')
	  send_file(path, :type => 'application/pdf', :disposition => 'inline')
	end

	def ley_388
		path=Rails.root.join('public','Ley_388_de_1997.pdf')
	  send_file(path, :type => 'application/pdf', :disposition => 'inline')
	end

	def estatuto_urbano
		path=Rails.root.join('public','Estatuto_Urbano_de_Soledad.pdf')
	  send_file(path, :type => 'application/pdf', :disposition => 'inline')
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
 def new
  end

  def create
 	  user= User.authenticate(params[:name], params[:password])
   	if user
      session[:user_id] = user.id
      redirect_to adm_board_path, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id]= nil
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to adm_board_path, notice: 'Se ha creado un nuevo usuario.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'El usuario fue editado.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/data_helper.rb
module DataHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/liq_expensas_helper.rb
module LiqExpensasHelper
end

app/helpers/pdfs_helper.rb
module PdfsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/data/_form.html.erb
<%= form_for(@datum) do |f| %>
  <% if @datum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@datum.errors.count, "error") %> prohibited this datum from being saved:</h2>

      <ul>
      <% @datum.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :definicion %><br>
    <%= f.text_field :definicion %>
  </div>
  <div class="field">
    <%= f.label :anio %><br>
    <%= f.text_field :anio %>
  </div>
  <div class="field">
    <%= f.label :siglas %><br>
    <%= f.text_field :siglas %>
  </div>
  <div class="field">
    <%= f.label :valor %><br>
    <%= f.text_field :valor %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/data/edit.html.erb
<h1>Editing datum</h1>

<%= render 'form' %>

<%= link_to 'Show', @datum %> |
<%= link_to 'Back', data_path %>

app/views/data/index.html.erb
<div id="user_nav">
    <% if current_user %>
    logged in as <%= current_user.name %>
    <%= link_to "log out" , log_out_path, "data-no-turbolink"  => true%>
    <% else %>
     <!--  <%= link_to "Sign up" , sign_up_path%> -->
      <%= link_to "log in" , log_in_path, "data-no-turbolink"  => true%>
    <% end %>
  </div>

<h1>Listing data</h1>

<table>
  <thead>
    <tr>
      <th>Definicion</th>
      <th>Anio</th>
      <th>Siglas</th>
      <th>Valor</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @data.each do |datum| %>
      <tr>
        <td><%= datum.definicion %></td>
        <td><%= datum.anio %></td>
        <td><%= datum.siglas %></td>
        <td><%= datum.valor %></td>
        <td><%= link_to 'Show', datum %></td>
        <td><%= link_to 'Edit', edit_datum_path(datum) %></td>
        <td><%= link_to 'Destroy', datum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Datum', new_datum_path %>

app/views/data/new.html.erb
<h1>New datum</h1>

<%= render 'form' %>

<%= link_to 'Back', data_path %>

app/views/data/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Definicion:</strong>
  <%= @datum.definicion %>
</p>

<p>
  <strong>Anio:</strong>
  <%= @datum.anio %>
</p>

<p>
  <strong>Siglas:</strong>
  <%= @datum.siglas %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @datum.valor %>
</p>

<%= link_to 'Edit', edit_datum_path(@datum) %> |
<%= link_to 'Back', data_path %>

app/views/home/contacto.html.erb
<div class="container clearfix">
    
    <div class="one-fourth">

      <h3>Información de Contacto</h3>

      <p>Cra 19 # 24A - 27, Piso 2<br/>
      Soledad-Atlantico</p>

        <p>Phone: (+57) 3755291<br/>
        Cel: +57 3006789821<br/>
        Email: curaduriasoledad1@gmail.com<br/>
        Web: www.curaduriasoledad1.com</p>
      
    </div><!-- end .one-fourth -->
    
    <div class="three-fourth last">

      <h3>Envíanos un Correo Electronico</h3>

      <form action="http://demo.samuli.me/smartstart/php/contact-send.php" method="post" class="contact-form">
      
        <p class="input-block">
          <label for="contact-name"><strong>Nombre</strong></label>
          <input type="text" name="name" value="" id="contact-name" required>
        </p>

        <p class="input-block">
          <label for="contact-email"><strong>Correo Electronico</strong></label>
          <input type="email" name="email" value="" id="contact-email" required>
        </p>
        
        <p class="input-block">
          <label for="contact-subject"><strong>Asunto</strong></label>
          <input type="text" name="subject" value="" id="contact-subject">
        </p>

        <p class="textarea-block">
          <label for="contact-message"><strong>Mensaje</strong></label>
          <textarea name="message" id="contact-message" cols="88" rows="6" required></textarea>
        </p>
      
        <div class="hidden">
          <label for="contact-spam-check">Do not fill out this field:</label>
          <input name="spam-check" type="text" value="" id="contact-spam-check" />
        </div>

        <input type="submit" value="Enviar">

        <div class="clear"></div>

      </form>

    </div><!-- end .three-fourth.last -->

  </div><!-- end .container -->
    
</section><!-- end #content -->
<!--[if !lte IE 6]><!-->
  

app/views/home/index.html.erb
<section id="content" class="container clearfix">

	<h2 class="slogan align-center">Curaduria Urbana N0.1 de Soledad</h2>

	<section id="features-slider" class="ss-slider">
	
		<article class="slide">
		
			<img src="<%= asset_path("features_img_1.jpg")%>" alt="" class="slide-bg-image" />
			
			<div class="slide-button">
				<span class="dropcap">1</span>
				<h5>Consulte el Estado de su Tramite</h5>
			</div>
		
			<div class="slide-content">
				<h2>Estado de Tramite</h2>
				<p>Envie un comunicado y consulte el estado actual de su tramite.</p>
				<p><a class="button" href="/contacto">Ver mas</a></p>
			</div>
			
		</article><!-- end .slide (Responsive Layout) -->
	
		<article class="slide">
		
			<img src="<%= asset_path("features_img_2.jpg")%>" alt="" class="slide-bg-image" />
		
			<div class="slide-button">		
				<span class="dropcap">2</span>
				<h5>Calcule sus Expensas</h5>
			</div>
			
			<div class="slide-content">
				<h2>Calcule sus Expensas</h2>
				<p>Por medio de nuestro sitio Web puede calcular las Expensas.</p>
				<p><a class="button" href="/liquidacion_de_expensas">Ver mas</a></p>
			</div>
			
		</article><!-- end .slide (HTML5 / CSS3) -->
	
		<article class="slide">
		
			<%= image_tag asset_path("features_img_1.jpg"), class: "slide-bg-image"%>
		
			<div class="slide-button">
				<span class="dropcap">3</span>
				<h5>Ayudas al Usuario</h5>
			</div>
			
			<div class="slide-content">
				<h2>Ayudas al Usuario</h2>
				<p>Por medio de esta opcion obtendra ayudas.</p>
				<p><a class="button" href="#">Ver mas</a></p>
			</div>
			
		</article><!-- end .slide (Easily Customisable) -->
	
		<article class="slide">
		
			<img src="<%= asset_path("features_img_3.jpg")%>" alt="" class="slide-bg-image" />
		
			<div class="slide-button">
				<span class="dropcap">4</span>
				<h5>Publicaciones </h5>
			</div>
			
			<div class="slide-content">
				<h2>Publicaciones</h2>
				<p>Consulte las ultimas publicaciones</p>
				<p><a class="button" href="#">Ver mas</a></p>
			</div>
			
		</article><!-- end .slide (Unique & Clean) -->
		
	</section><!-- end #features-slider -->


</section><!-- end #content -->


<!--[if !lte IE 6]><!-->
	
<!--<![endif]-->


<!-- Mirrored from demo.samuli.me/smartstart/index.html by HTTrack Website Copier/3.x [XR&CO'2013], Thu, 13 Feb 2014 22:54:23 GMT -->

app/views/home/misionv.html.erb
<section id="content" class="container clearfix">

	<header class="page-header">

		<h2 style="font-size: 19px;"  class="page-description">¿Quienes Somos?</h2>
		
	</header><!-- end .page-header -->


		<ul class="tabs-nav">

			<li class="active">
				<a href="#tab1">Misión</a>
			</li>

			<li>
				<a href="#tab2">Visión</a>
			</li>

		</ul><!-- end .tabs-nav -->

		<div class="tabs-container">

			<div class="tab-content" id="tab1">
				<p>La <strong>Curaduría Urbana N° 1 de Soledad (Atlántico)</strong> es una entidad cuya misión es brindarles a la comunidad la mejor información acerca de las reglas para llevar a cabo proyectos urbanísticos o arquitectónicos, dispuestos siempre a prestarles el mejor servicio.</p>
				<p>En La Curaduría Urbana N° 1 de Soledad (Atlántico) ofrecemos el servicio de evaluación de los requisitos técnicos y legales que deben cumplir todos y cada uno de los proyectos urbanísticos y/o arquitectónicos para adquirir una licencia que se adapte a sus necesidades. Todo esto prestando un servicio de calidad y velando por la satisfacción de las necesidades de nuestros clientes, haciendo uso de personal calificado y utilizando las ultimas tecnologías.</p>
			</div><!-- end #tab1 -->

			<div class="tab-content" id="tab2">
				<p>Ser la entidad líder en la prestación de nuestro servicio en la Costa Norte Colombiana. Lo anterior con el apoyo y la participación de todos los miembros de la empresa, por medio de la planeación, el compromiso, la disposición y la preparación de nuestro personal en la realización de sus labores, con el fin de ofrecer un servicio de calidad y garantizando el cumplimiento de los requisitos legales y la satisfacción de las  necesidades de nuestros clientes.</p>
				<p>Alcanzar y mantener permanentemente la calidad en el servicio público prestado a través del trabajo sistemático y en el mejoramiento permanente de los procesos de estudiar, tramitar y expedir licencias. Todo lo anterior con el objeto de proporcionar al cliente la confianza que se alcanza con la calidad establecida en los servicios y la contribución en el desarrollo planificado </p>
			</div><!-- end #tab2 -->

		</div><!-- end .tabs-container -->


</section><!-- end #content -->

<!--[if !lte IE 6]><!-->

<!--<![endif]-->

app/views/home/misionvision.html.erb
<section id="content" class="container clearfix">

	<header class="page-header">

		<h2 style="font-size: 19px;"  class="page-description">¿Quienes Somos?</h2>
		
	</header><!-- end .page-header -->


		<ul class="tabs-nav">

			<li class="active">
				<a href="#tab1">Misión</a>
			</li>

			<li>
				<a href="#tab2">Visión</a>
			</li>

		</ul><!-- end .tabs-nav -->

		<div class="tabs-container">

			<div class="tab-content" id="tab1">
				<p>La <strong>Curaduría Urbana N° 1 de Soledad (Atlántico)</strong> es una entidad cuya misión es brindarles a la comunidad la mejor información acerca de las reglas para llevar a cabo proyectos urbanísticos o arquitectónicos, dispuestos siempre a prestarles el mejor servicio.</p>
				<p>En La Curaduría Urbana N° 1 de Soledad (Atlántico) ofrecemos el servicio de evaluación de los requisitos técnicos y legales que deben cumplir todos y cada uno de los proyectos urbanísticos y/o arquitectónicos para adquirir una licencia que se adapte a sus necesidades. Todo esto prestando un servicio de calidad y velando por la satisfacción de las necesidades de nuestros clientes, haciendo uso de personal calificado y utilizando las ultimas tecnologías.</p>
			</div><!-- end #tab1 -->

			<div class="tab-content" id="tab2">
				<p>Ser la entidad líder en la prestación de nuestro servicio en la Costa Norte Colombiana. Lo anterior con el apoyo y la participación de todos los miembros de la empresa, por medio de la planeación, el compromiso, la disposición y la preparación de nuestro personal en la realización de sus labores, con el fin de ofrecer un servicio de calidad y garantizando el cumplimiento de los requisitos legales y la satisfacción de las  necesidades de nuestros clientes.</p>
				<p>Alcanzar y mantener permanentemente la calidad en el servicio público prestado a través del trabajo sistemático y en el mejoramiento permanente de los procesos de estudiar, tramitar y expedir licencias. Todo lo anterior con el objeto de proporcionar al cliente la confianza que se alcanza con la calidad establecida en los servicios y la contribución en el desarrollo planificado </p>
			</div><!-- end #tab2 -->

		</div><!-- end .tabs-container -->


</section><!-- end #content -->

<!--[if !lte IE 6]><!-->

<!--<![endif]-->

app/views/home/nuestrasede.html.erb
<section id="content" class="clearfix">

  <div class="container clearfix">

    <header class="page-header">
    
      <h1 class="page-title">Nos encontramos en la Cra 19 # 24A - 27 Piso 2, Soledad-Atlantico</h1>
      
    </header><!-- end .page-header -->

  </div><!-- end .container -->

  <section id="map">
    <p class="container">Something went wrong... Try to enable your JavaScript!</p>
  </section><!-- end #map -->
</section><!-- end #content -->


<!--[if !lte IE 6]><!-->
  
<!--<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>  
    <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <title><%= content_for?(:yield) ? yield(:title) : "Curaduria" %></title>
  <meta name="description" content="">
  <meta name="author" content="">
  <!-- HTML5 Shiv + detect touch events -->
  <%= javascript_include_tag "modernizr.custom.js" %>

  <!-- HTML5 video player -->
  <%= javascript_include_tag "video.min.js" %>

</head>
<body>
  <header id="header" class="container clearfix">
    <a href='<%= root_path %>' id="logo">
      <img src="<%= asset_path("logo.png") %>" width: 140px alt="SmartStart">
    </a>
  <nav id="main-nav">
    <ul>
      <li class="current">
        <a href='<%= root_path %>' >Inicio</a>
      </li>
      <li>
        <a href='<%= servicios_path %>'>Servicios</a>
      </li>
      <li>
        <a href= '<%= normatividad_path %>' >Normatividad</a>
      </li>
      <li>
        <a href="#">Quienes Somos</a>
        <ul>
          <li><a href='<%= misionv_path %>'>Misión y Visión</a></li>
          <li><a href='<%= nuestrasede_path %>'>Nuestra Sede</a></li>
          <li><a href="#">El Curador Urbano</a></li>
        </ul>
      </li>
      <li>
        <a href='<%= contacto_path %>'>Peticiones</a>
      </li>
    </ul>
  </nav><!-- end #main-nav -->
</header><!-- end #header -->
<%= yield %>

<footer id="footer" class="clearfix">
  <div class="container">
    <div class="three-fourth">
      <nav id="footer-nav" class="clearfix">
        <ul>
          <li><a href="index.html">Inicio</a></li>
          <li><a href="elements.html">Servicios</a></li>
          <li><a href="blog.html">Normatividad</a></li>
          <li><a href="portfolio-4-columns.html">Quienes Somos</a></li>
          <li><a href='<% contacto_path %>'>Peticiones</a></li>
        </ul>
      </nav><!-- end #footer-nav -->
      <ul class="contact-info">
        <li class="address">Soledad Cra 19 No. 12-45</li>
        <li class="phone">3000000</li>
        <li class="email"><a href="mailto:contact@companyname.com">curaduriaN1soledad@gmail.com</a></li>
      </ul><!-- end .contact-info -->
    </div><!-- end .three-fourth -->
    <div class="one-fourth last">

      <span class="title">Stay connected</span>

      <ul class="social-links">
        <li class="twitter"><a href="#">Twitter</a></li>
        <li class="facebook"><a href="#">Facebook</a></li>
        <li class="youtube"><a href="#">YouTube</a></li>
        <li class="skype"><a href="#">Skype</a></li>
      </ul><!-- end .social-links -->

    </div><!-- end .one-fourth.last -->
    
  </div><!-- end .container -->

</footer><!-- end #footer -->

<footer id="footer-bottom" class="clearfix">

  <div class="container">

    <ul>
      <li>SmartStart &copy; 2012</li>
      <li><a href="#">Legal Notice</a></li>
      <li><a href="#">Terms</a></li>
    </ul>

  </div><!-- end .container -->

</footer><!-- end #footer-bottom -->


<%= javascript_include_tag "application" %>
<%= javascript_include_tag "jquery.ui.widget.min.js" %>
<%= javascript_include_tag "respond.min.js" %>
  <%= javascript_include_tag "jquery.easing-1.3.min.js"%>
 <% javascript_include_tag "jquery.fancybox.pack.js" %>
  <%= javascript_include_tag "jquery.smartStartSlider.min.js"%>
  <%= javascript_include_tag "jquery.jcarousel.min.js" %>
  <%= javascript_include_tag "jquery.cycle.all.min.js" %>
  <% javascript_include_tag "jquery.isotope.min.js" %>
  <% javascript_include_tag "audioplayerv1.min.js" %>
  <%= javascript_include_tag "http://maps.google.com/maps/api/js?sensor=false" %>
 <%= javascript_include_tag "jquery.gmap.min.js" %>
 <%= javascript_include_tag "jquery.touchSwipe.min.js" %>
  <%= javascript_include_tag "jquery.colorbox-min.js" %>
  <%= javascript_include_tag "custom.js" %>
  <%= yield :javascripts %>
</body>
</html>

app/views/liq_expensas/index.html.erb
<section id="content" class="container clearfix">
	<div class="one-third">
		<h4>Liquidación de expensas</h4>
		  <ul>
					<li><a class="inline_content" href="/cargo_fijo_otros_usos">Cargo fijo otros usos</a></li>
					<li><a class="inline_content" href="/cargo_fijo_uso_residencial">Cargo fijo uso residencial</a></li>
					<li><a class="inline_content" href="/cargo_variable_uso_residencial">Cargo variable uso residencial</a></li>
					<li><a class="inline_content" href="/cargo_variable_otros_usos">Cargo variable otros usos</a></li>
					
		  </ul>
		
	</div><!-- end .one-third -->
	</section>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Password</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>